In [72]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[(arr >= 20) & (arr < 40)])
print(arr[(arr < 20) | (arr > 40)])

[20 30]
[10 50]


In [68]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[arr >= 20])
print(arr != 20)

[20 30 40 50]
[ True False  True  True  True]


In [62]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
    ])
print(arr)
print(arr[1,2])
print(arr[0,:])
print(arr[:,1])
print(arr[: ,0:2])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
60
[10 20 30]
[20 50 80]
[[10 20]
 [40 50]
 [70 80]]


In [52]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr[0][1])

[[1 2]
 [3 4]]
2


In [50]:
import numpy as np
arr = np.array([[[1,2], [3,4]],
                [[5,6],[7,8]]
                ])
print(arr)
print(arr[1][1][1])
arr[1][1] = 5
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
[[[1 2]
  [3 4]]

 [[5 6]
  [5 5]]]


In [46]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
matrix[0:2,0:2]
matrix[0:3,1:3]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [ ]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
import numpy as np
lists = np.array([[1,2,3], [4,5,6]])
print(lists.ndim)
print(lists.dtype)
print(lists.size)
print(lists.itemsize)
print(lists.nbytes)
print(lists.T)
print(lists.shape)

2
int64
6
8
48
[[1 4]
 [2 5]
 [3 6]]
(2, 3)


In [37]:
import numpy as np
arr = np.array([1,2,3])
print(arr.ndim)

1


In [36]:
import numpy as np
arr = np.linspace(0,20,4)

print(arr)

[ 0.          6.66666667 13.33333333 20.        ]


In [28]:
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
import numpy as np
intType = np.array([1,2,3], dtype=np.int64)
print(type(intType))
print(intType)
print(intType.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int64


In [21]:
import numpy as np
list_1 = [1,3,4,5,6]
list_ans = np.array(list_1)
print(list_ans)
print(type(list_ans))
list_2 = [[1,2,3], [4,5,6], [7,8,9]]
list_ans2 = np.array(list_2)
print(list_ans2)

[1 3 4 5 6]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
import numpy as np
one = np.ones((2,3))
print(f"one print \n {one}")
full = np.full((2,2),7)
print(full)

one print 
 [[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


In [16]:
import numpy as np
zeros = np.zeros((2,3))
print("zeros number print\n", zeros)

zeros number print
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
import time 
p_np = [1,2,3,4]
print(p_np* 2)
n_np = np.array([1,2,3,4])
print(n_np * 2)
start = time.time()
p_np = [i * 2 for i in range(1000000)]
print(time.time() - start)

start = time.time()
n_np = np.arange(1000000) * 2
print(time.time() - start)



[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
3.0994415283203125e-05
2.09808349609375e-05


In [8]:
import numpy as np
print(np.__version__)

2.5.0


In [ ]:
import numpy as np

In [7]:
num = [1,2,3]
print(num * 2)
n = np.array([1,2,3])
print(n *2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [4]:
import numpy as np
arr_1 = np.array([1,2,3,4,5,6])
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
print(arr_2)
print(type(arr_1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
