In [66]:
class MeraLR:
    def __init__(self):
        self.m= None
        self.b= None
    def fit(self, X_train, y_train):
        num =0
        den =0
        for i in range(X_train.shape[0]):
            num = num+ ((X_train[i] - X_train.mean()) * (y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean()) * (X_train[i] - X_train.mean()))
        self.m = num/den
        self.b = y_train.mean()-(self.m * X_train.mean())
        print(self.m)
        print(self.b)
    def predict(self,X_test):
        print(X_test)
        return self.m * X_test + self.b


In [67]:
import numpy as np
import pandas as pd


In [68]:
df = pd.read_csv('/Users/nikhilbishnoi/Desktop - Nikhil’s MacBook Air - 1/python/placement_data.csv/placement_data.csv')


In [69]:
df.head()

,CGPA,Placement_Package_LPA
0,6.87,9.06
1,9.75,13.43
2,8.66,12.19
3,7.99,10.37
4,5.78,10.30


In [70]:
x = df.iloc[:,0].values
y = df.iloc[:,-1].values

In [71]:
x

array([6.87, 9.75, 8.66, 7.99, 5.78, 5.78, 5.29, 9.33, 8.01, 8.54, 5.1 ,
       9.85, 9.16, 6.06, 5.91, 5.92, 6.52, 7.62, 7.16, 6.46, 8.06, 5.7 ,
       6.46, 6.83, 7.28, 8.93, 6.  , 7.57, 7.96, 5.23, 8.04, 5.85, 5.33,
       9.74, 9.83, 9.04, 6.52, 5.49, 8.42, 7.2 , 5.61, 7.48, 5.17, 9.55,
       6.29, 8.31, 6.56, 7.6 , 7.73, 5.92, 9.85, 8.88, 9.7 , 9.47, 7.99,
       9.61, 5.44, 5.98, 5.23, 6.63, 6.94, 6.36, 9.14, 6.78, 6.4 , 7.71,
       5.7 , 9.01, 5.37, 9.93, 8.86, 5.99, 5.03, 9.08, 8.53, 8.65, 8.86,
       5.37, 6.79, 5.58, 9.32, 8.12, 6.65, 5.32, 6.55, 6.63, 8.65, 8.19,
       9.44, 7.36, 5.6 , 8.57, 8.8 , 7.81, 8.85, 7.47, 7.61, 7.14, 5.13,
       5.54, 5.16, 8.18, 6.57, 7.54, 9.54, 6.25, 7.05, 8.78, 6.14, 5.38,
       6.45, 5.81, 9.65, 9.04, 8.17, 9.36, 9.02, 5.93, 9.46, 7.7 , 9.04,
       9.48, 6.59, 5.55, 6.14, 7.14, 9.09, 9.3 , 5.03, 7.55, 7.09, 6.11,
       5.6 , 6.69, 9.71, 6.62, 7.59, 8.52, 6.82, 9.86, 9.81, 6.26, 7.49,
       6.5 , 6.42, 5.18, 8.05, 7.51, 5.26, 6.39, 9.

In [72]:
y

array([ 9.06, 13.43, 12.19, 10.37, 10.3 ,  8.91,  6.66, 13.35, 10.14,
       12.54,  8.78, 12.5 , 13.46,  9.18,  9.41, 10.5 ,  9.08,  9.89,
        9.2 ,  8.44, 11.09,  8.68,  9.53, 10.52, 10.25, 13.67,  8.44,
       13.3 , 11.68,  6.92, 10.08,  9.  ,  7.67, 13.9 , 13.77, 12.28,
        8.48,  6.57, 11.16, 11.  ,  8.45,  9.23,  7.88, 13.35,  8.16,
       11.63,  9.43,  9.48, 11.13,  9.16, 14.4 , 13.21, 11.76, 11.93,
       11.6 , 13.55,  8.54, 12.53,  8.35, 10.59, 10.78,  9.78, 12.15,
       10.39,  8.41, 10.52,  7.85, 12.39, 10.26, 11.55, 12.82,  7.08,
        7.06, 13.48, 11.8 , 10.8 , 11.42,  8.62,  8.92,  8.41, 12.73,
       10.59, 11.62,  8.52,  7.33,  9.64, 11.22, 12.18, 12.04, 10.22,
        8.72, 12.65, 10.86, 10.54, 11.65,  9.81, 12.4 , 10.47,  6.4 ,
        9.07,  9.81, 12.35,  7.86, 10.06, 14.21,  8.29, 10.4 , 12.81,
        7.94,  7.9 ,  6.  ,  7.45, 12.83, 11.1 , 12.94, 11.3 , 11.88,
        8.75, 14.29,  9.3 , 13.51, 12.89,  8.43,  8.62,  9.07,  9.47,
       12.48, 12.27,

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train ,y_test = train_test_split(x,y, test_size=0.2, random_state=2)

In [74]:
X_train.shape

(160,)

In [75]:
lr = MeraLR()

In [76]:
lr.fit(X_train,y_train)

1.1726785813584433
1.7825534091434054


In [77]:
X_train.shape[0]

160

In [78]:
X_train[0]

np.float64(8.52)

In [79]:
X_train.mean()

np.float64(7.351499999999999)

In [80]:
X_train

array([8.52, 7.68, 5.81, 5.55, 5.38, 6.26, 7.48, 7.09, 9.81, 5.78, 8.64,
       5.16, 9.85, 7.78, 7.28, 7.36, 5.7 , 8.01, 7.56, 5.87, 7.96, 6.69,
       8.85, 5.17, 7.95, 6.65, 6.29, 7.05, 6.14, 6.5 , 6.71, 6.6 , 8.05,
       5.58, 9.75, 7.7 , 9.5 , 6.39, 6.84, 7.65, 7.51, 6.52, 5.08, 5.69,
       9.14, 6.87, 7.57, 8.81, 5.13, 9.46, 8.06, 6.19, 8.36, 7.49, 5.37,
       8.04, 9.93, 7.62, 6.63, 5.57, 8.17, 9.3 , 9.86, 9.49, 7.81, 6.2 ,
       5.7 , 9.61, 6.52, 5.72, 8.57, 5.54, 9.04, 9.49, 8.53, 5.47, 8.16,
       6.42, 8.63, 8.19, 5.6 , 6.55, 7.16, 7.14, 8.18, 7.14, 5.45, 6.62,
       6.36, 8.12, 5.37, 7.55, 5.44, 6.46, 8.65, 8.86, 6.94, 9.83, 5.61,
       6.82, 8.86, 7.45, 6.  , 5.33, 6.75, 7.61, 5.32, 6.45, 6.25, 9.08,
       5.93, 9.54, 5.18, 6.21, 9.44, 7.59, 7.2 , 5.92, 9.09, 5.6 , 9.85,
       9.7 , 9.32, 8.3 , 9.48, 6.21, 6.56, 9.44, 9.93, 9.01, 9.39, 5.23,
       9.74, 8.42, 7.54, 8.88, 8.78, 8.39, 5.78, 6.57, 5.93, 5.49, 9.02,
       6.14, 5.26, 5.85, 6.78, 7.6 , 6.7 , 7.47, 6.

In [81]:
print(lr.predict(X_test[0]))

9.65
13.098901719252384
